set(_CATKIN_CURRENT_PACKAGE "nubot_hwcontroller")
set(nubot_hwcontroller_VERSION "1.0.0")
set(nubot_hwcontroller_MAINTAINER "Kaihong HUANG <Kaihong.huang11@gmail.com>")
set(nubot_hwcontroller_PACKAGE_FORMAT "1")
set(nubot_hwcontroller_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_standalone" "realtime_tools" "dynamic_reconfigure" "nubot_common")
set(nubot_hwcontroller_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(nubot_hwcontroller_BUILDTOOL_DEPENDS "catkin")
set(nubot_hwcontroller_BUILDTOOL_EXPORT_DEPENDS )
set(nubot_hwcontroller_EXEC_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(nubot_hwcontroller_RUN_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(nubot_hwcontroller_TEST_DEPENDS )
set(nubot_hwcontroller_DOC_DEPENDS )
set(nubot_hwcontroller_URL_WEBSITE "")
set(nubot_hwcontroller_URL_BUGTRACKER "")
set(nubot_hwcontroller_URL_REPOSITORY "")
set(nubot_hwcontroller_DEPRECATED "")