set(_CATKIN_CURRENT_PACKAGE "tis_camera")
set(tis_camera_VERSION "0.1.0")
set(tis_camera_MAINTAINER "jensen <jensen@todo.todo>")
set(tis_camera_PACKAGE_FORMAT "2")
set(tis_camera_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(tis_camera_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(tis_camera_BUILDTOOL_DEPENDS "catkin")
set(tis_camera_BUILDTOOL_EXPORT_DEPENDS )
set(tis_camera_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(tis_camera_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(tis_camera_TEST_DEPENDS )
set(tis_camera_DOC_DEPENDS )
set(tis_camera_URL_WEBSITE "")
set(tis_camera_URL_BUGTRACKER "")
set(tis_camera_URL_REPOSITORY "")
set(tis_camera_DEPRECATED "")