set(plot_tool_SETUP_PY_VERSION "0.0.0")
set(plot_tool_SETUP_PY_SCRIPTS "")
set(plot_tool_SETUP_PY_PACKAGES "")
set(plot_tool_SETUP_PY_PACKAGE_DIRS "./")
set(plot_tool_SETUP_PY_MODULES "")
set(plot_tool_SETUP_PY_MODULE_DIRS "")