set(_CATKIN_CURRENT_PACKAGE "calibration_util")
set(calibration_util_VERSION "0.0.0")
set(calibration_util_MAINTAINER "nubot9 <nubot9@todo.todo>")
set(calibration_util_PACKAGE_FORMAT "1")
set(calibration_util_BUILD_DEPENDS "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(calibration_util_BUILD_EXPORT_DEPENDS "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(calibration_util_BUILDTOOL_DEPENDS "catkin")
set(calibration_util_BUILDTOOL_EXPORT_DEPENDS )
set(calibration_util_EXEC_DEPENDS "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(calibration_util_RUN_DEPENDS "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(calibration_util_TEST_DEPENDS )
set(calibration_util_DOC_DEPENDS )
set(calibration_util_URL_WEBSITE "")
set(calibration_util_URL_BUGTRACKER "")
set(calibration_util_URL_REPOSITORY "")
set(calibration_util_DEPRECATED "")