// Generated by gencpp from file plot_tool/PlotPose.msg
// DO NOT EDIT!


#ifndef PLOT_TOOL_MESSAGE_PLOTPOSE_H
#define PLOT_TOOL_MESSAGE_PLOTPOSE_H

#include <ros/service_traits.h>


#include <plot_tool/PlotPoseRequest.h>
#include <plot_tool/PlotPoseResponse.h>


namespace plot_tool
{

struct PlotPose
{

typedef PlotPoseRequest Request;
typedef PlotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlotPose
} // namespace plot_tool


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plot_tool::PlotPose > {
  static const char* value()
  {
    return "0b57137281cf86b445cc0e3821c92f9e";
  }

  static const char* value(const ::plot_tool::PlotPose&) { return value(); }
};

template<>
struct DataType< ::plot_tool::PlotPose > {
  static const char* value()
  {
    return "plot_tool/PlotPose";
  }

  static const char* value(const ::plot_tool::PlotPose&) { return value(); }
};


// service_traits::MD5Sum< ::plot_tool::PlotPoseRequest> should match 
// service_traits::MD5Sum< ::plot_tool::PlotPose > 
template<>
struct MD5Sum< ::plot_tool::PlotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plot_tool::PlotPose >::value();
  }
  static const char* value(const ::plot_tool::PlotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plot_tool::PlotPoseRequest> should match 
// service_traits::DataType< ::plot_tool::PlotPose > 
template<>
struct DataType< ::plot_tool::PlotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::plot_tool::PlotPose >::value();
  }
  static const char* value(const ::plot_tool::PlotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plot_tool::PlotPoseResponse> should match 
// service_traits::MD5Sum< ::plot_tool::PlotPose > 
template<>
struct MD5Sum< ::plot_tool::PlotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plot_tool::PlotPose >::value();
  }
  static const char* value(const ::plot_tool::PlotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plot_tool::PlotPoseResponse> should match 
// service_traits::DataType< ::plot_tool::PlotPose > 
template<>
struct DataType< ::plot_tool::PlotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::plot_tool::PlotPose >::value();
  }
  static const char* value(const ::plot_tool::PlotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLOT_TOOL_MESSAGE_PLOTPOSE_H
