set(_CATKIN_CURRENT_PACKAGE "front_vision")
set(front_vision_VERSION "0.0.0")
set(front_vision_MAINTAINER "nubot <nubot.nudt@gmail.com>, nubot <nubot.nudt@outlook.com>")
set(front_vision_PACKAGE_FORMAT "1")
set(front_vision_BUILD_DEPENDS "nubot_common" "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "message_generation" "opencv2/" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(front_vision_BUILD_EXPORT_DEPENDS "nubot_common" "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "message_generation" "opencv2/" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(front_vision_BUILDTOOL_DEPENDS "catkin")
set(front_vision_BUILDTOOL_EXPORT_DEPENDS )
set(front_vision_EXEC_DEPENDS "nubot_common" "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "message_generation" "opencv2/" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(front_vision_RUN_DEPENDS "nubot_common" "cv_bridge" "dynamic_reconfigure" "image_transport" "message_filters" "message_generation" "opencv2/" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(front_vision_TEST_DEPENDS )
set(front_vision_DOC_DEPENDS )
set(front_vision_URL_WEBSITE "https://github.com/nubot-nudt/nubot_ws")
set(front_vision_URL_BUGTRACKER "")
set(front_vision_URL_REPOSITORY "")
set(front_vision_DEPRECATED "")