(cl:in-package nubot_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          AGENTID-VAL
          AGENTID
          TARGETNUM1-VAL
          TARGETNUM1
          TARGETNUM2-VAL
          TARGETNUM2
          TARGETNUM3-VAL
          TARGETNUM3
          TARGETNUM4-VAL
          TARGETNUM4
          STATICPASSNUM-VAL
          STATICPASSNUM
          STATICCATCHNUM-VAL
          STATICCATCHNUM
          POS-VAL
          POS
          HEADING-VAL
          HEADING
          VROT-VAL
          VROT
          VTRANS-VAL
          VTRANS
          ISKICK-VAL
          ISKICK
          ISVALID-VAL
          ISVALID
          ISSTUCK-VAL
          ISSTUCK
          ISDRIBBLE-VAL
          ISDRIBBLE
          CURRENT_ROLE-VAL
          CURRENT_ROLE
          ROLE_TIME-VAL
          ROLE_TIME
          TARGET-VAL
          TARGET
))