set(_CATKIN_CURRENT_PACKAGE "nubot_control")
set(nubot_control_VERSION "0.0.0")
set(nubot_control_MAINTAINER "nubot <nubot@todo.todo>")
set(nubot_control_PACKAGE_FORMAT "1")
set(nubot_control_BUILD_DEPENDS "nubot_common" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "world_model" "cmake_modules")
set(nubot_control_BUILD_EXPORT_DEPENDS "cmake_modules" "nubot_common" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "world_model")
set(nubot_control_BUILDTOOL_DEPENDS "catkin")
set(nubot_control_BUILDTOOL_EXPORT_DEPENDS )
set(nubot_control_EXEC_DEPENDS "cmake_modules" "nubot_common" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "world_model")
set(nubot_control_RUN_DEPENDS "cmake_modules" "nubot_common" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "world_model")
set(nubot_control_TEST_DEPENDS )
set(nubot_control_DOC_DEPENDS )
set(nubot_control_URL_WEBSITE "")
set(nubot_control_URL_BUGTRACKER "")
set(nubot_control_URL_REPOSITORY "")
set(nubot_control_DEPRECATED "")