set(_CATKIN_CURRENT_PACKAGE "cmake_modules")
set(cmake_modules_VERSION "0.3.2")
set(cmake_modules_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(cmake_modules_PACKAGE_FORMAT "1")
set(cmake_modules_BUILD_DEPENDS )
set(cmake_modules_BUILD_EXPORT_DEPENDS )
set(cmake_modules_BUILDTOOL_DEPENDS "catkin")
set(cmake_modules_BUILDTOOL_EXPORT_DEPENDS )
set(cmake_modules_EXEC_DEPENDS )
set(cmake_modules_RUN_DEPENDS )
set(cmake_modules_TEST_DEPENDS )
set(cmake_modules_DOC_DEPENDS )
set(cmake_modules_URL_WEBSITE "")
set(cmake_modules_URL_BUGTRACKER "https://github.com/ros/cmake_modules/issues")
set(cmake_modules_URL_REPOSITORY "https://github.com/ros/cmake_modules")
set(cmake_modules_DEPRECATED "")