set(_CATKIN_CURRENT_PACKAGE "simulation_interface")
set(simulation_interface_VERSION "0.0.0")
set(simulation_interface_MAINTAINER "nubot <nubot.nudt@gmail.com>, nubot <nubot.nudt@outlook.com>")
set(simulation_interface_PACKAGE_FORMAT "1")
set(simulation_interface_BUILD_DEPENDS "nubot_common" "world_model" "roscpp" "rospy" "message_filters" "message_generation")
set(simulation_interface_BUILD_EXPORT_DEPENDS "nubot_common" "world_model" "roscpp" "rospy" "message_filters" "message_generation")
set(simulation_interface_BUILDTOOL_DEPENDS "catkin")
set(simulation_interface_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_interface_EXEC_DEPENDS "nubot_common" "world_model" "roscpp" "rospy" "message_filters" "message_generation")
set(simulation_interface_RUN_DEPENDS "nubot_common" "world_model" "roscpp" "rospy" "message_filters" "message_generation")
set(simulation_interface_TEST_DEPENDS )
set(simulation_interface_DOC_DEPENDS )
set(simulation_interface_URL_WEBSITE "https://github.com/nubot-nudt/nubot_ws")
set(simulation_interface_URL_BUGTRACKER "")
set(simulation_interface_URL_REPOSITORY "")
set(simulation_interface_DEPRECATED "")