set(_CATKIN_CURRENT_PACKAGE "plot_tool")
set(plot_tool_VERSION "0.0.0")
set(plot_tool_MAINTAINER "pchen <pchen@clearpathrobotics.com>")
set(plot_tool_PACKAGE_FORMAT "1")
set(plot_tool_BUILD_DEPENDS "roscpp" "rospy" "nav_msgs" "std_msgs" "geometry_msgs")
set(plot_tool_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs" "nav_msgs" "roscpp" "rospy")
set(plot_tool_BUILDTOOL_DEPENDS "catkin")
set(plot_tool_BUILDTOOL_EXPORT_DEPENDS )
set(plot_tool_EXEC_DEPENDS "geometry_msgs" "std_msgs" "nav_msgs" "roscpp" "rospy")
set(plot_tool_RUN_DEPENDS "geometry_msgs" "std_msgs" "nav_msgs" "roscpp" "rospy")
set(plot_tool_TEST_DEPENDS )
set(plot_tool_DOC_DEPENDS )
set(plot_tool_URL_WEBSITE "")
set(plot_tool_URL_BUGTRACKER "")
set(plot_tool_URL_REPOSITORY "")
set(plot_tool_DEPRECATED "")