set(_CATKIN_CURRENT_PACKAGE "sensor_gyro")
set(sensor_gyro_VERSION "0.1.0")
set(sensor_gyro_MAINTAINER "lzz <lzz@todo.todo>")
set(sensor_gyro_PACKAGE_FORMAT "1")
set(sensor_gyro_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_standalone" "realtime_tools" "dynamic_reconfigure" "nubot_common")
set(sensor_gyro_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(sensor_gyro_BUILDTOOL_DEPENDS "catkin")
set(sensor_gyro_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_gyro_EXEC_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(sensor_gyro_RUN_DEPENDS "roscpp" "std_msgs" "message_generation" "nubot_common" "dynamic_reconfigure" "realtime_tools")
set(sensor_gyro_TEST_DEPENDS )
set(sensor_gyro_DOC_DEPENDS )
set(sensor_gyro_URL_WEBSITE "")
set(sensor_gyro_URL_BUGTRACKER "")
set(sensor_gyro_URL_REPOSITORY "")
set(sensor_gyro_DEPRECATED "")