# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from plot_tool/PlotPoseRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PlotPoseRequest(genpy.Message):
  _md5sum = "0b57137281cf86b445cc0e3821c92f9e"
  _type = "plot_tool/PlotPoseRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
geometry_msgs/Pose msg
uint32 series
bool append
char symbol
uint32 symbol_size

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['msg','series','append','symbol','symbol_size']
  _slot_types = ['geometry_msgs/Pose','uint32','bool','char','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msg,series,append,symbol,symbol_size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlotPoseRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.msg is None:
        self.msg = geometry_msgs.msg.Pose()
      if self.series is None:
        self.series = 0
      if self.append is None:
        self.append = False
      if self.symbol is None:
        self.symbol = 0
      if self.symbol_size is None:
        self.symbol_size = 0
    else:
      self.msg = geometry_msgs.msg.Pose()
      self.series = 0
      self.append = False
      self.symbol = 0
      self.symbol_size = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dI2BI().pack(_x.msg.position.x, _x.msg.position.y, _x.msg.position.z, _x.msg.orientation.x, _x.msg.orientation.y, _x.msg.orientation.z, _x.msg.orientation.w, _x.series, _x.append, _x.symbol, _x.symbol_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.msg is None:
        self.msg = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 66
      (_x.msg.position.x, _x.msg.position.y, _x.msg.position.z, _x.msg.orientation.x, _x.msg.orientation.y, _x.msg.orientation.z, _x.msg.orientation.w, _x.series, _x.append, _x.symbol, _x.symbol_size,) = _get_struct_7dI2BI().unpack(str[start:end])
      self.append = bool(self.append)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dI2BI().pack(_x.msg.position.x, _x.msg.position.y, _x.msg.position.z, _x.msg.orientation.x, _x.msg.orientation.y, _x.msg.orientation.z, _x.msg.orientation.w, _x.series, _x.append, _x.symbol, _x.symbol_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.msg is None:
        self.msg = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 66
      (_x.msg.position.x, _x.msg.position.y, _x.msg.position.z, _x.msg.orientation.x, _x.msg.orientation.y, _x.msg.orientation.z, _x.msg.orientation.w, _x.series, _x.append, _x.symbol, _x.symbol_size,) = _get_struct_7dI2BI().unpack(str[start:end])
      self.append = bool(self.append)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dI2BI = None
def _get_struct_7dI2BI():
    global _struct_7dI2BI
    if _struct_7dI2BI is None:
        _struct_7dI2BI = struct.Struct("<7dI2BI")
    return _struct_7dI2BI
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from plot_tool/PlotPoseResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PlotPoseResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "plot_tool/PlotPoseResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlotPoseResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class PlotPose(object):
  _type          = 'plot_tool/PlotPose'
  _md5sum = '0b57137281cf86b445cc0e3821c92f9e'
  _request_class  = PlotPoseRequest
  _response_class = PlotPoseResponse
